axis-remote
===========

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<options,OPTIONS>>
. <<see-also,SEE ALSO>>
. <<history,HISTORY>>
. <<bugs,BUGS>>
. <<author,AUTHOR>>
. <<reporting-bugs,REPORTING BUGS>>
. <<copyright,COPYRIGHT>>


===== [[name]]NAME
axis-remote -- AXIS Remote Interface


===== [[synopsis]]SYNOPSIS
axis-remote __OPTIONS__|__FILENAME__


===== [[description]]DESCRIPTION
**axis-remote** is a small script that triggers commands in a running AXIS GUI.
Use **axis-remote --help** for further information.


===== [[options]]OPTIONS

**--ping**, **-p**
Check whether AXIS is running.

**--reload**, **-r**
Make AXIS reload the currently loaded file.

**--clear**, **-c**
Make AXIS clear the backplot.

**--quit**, **-q**
Make AXIS quit.

**--help**, **-h**, **-?**
Display a list of valid parameters for **axis-remote**.

**--mdi COMMAND**, **-m COMMAND**
Run the MDI command **COMMAND**.

**FILENAME**
Load the G-code file **FILENAME**.


===== [[see-also]]SEE ALSO
**axis(1)**

Much more information about LinuxCNC and HAL is available in the LinuxCNC
and HAL User Manuals, found at /usr/share/doc/linuxcnc/.



===== [[history]]HISTORY



===== [[bugs]]BUGS
None known at this time. 
.PP


===== [[author]]AUTHOR
This man page written by Alex Joni, as part of the LinuxCNC project.


===== [[reporting-bugs]]REPORTING BUGS
Report bugs to alex_joni AT users DOT sourceforge DOT net


===== [[copyright]]COPYRIGHT
Copyright \(co 2007 Alex Joni.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
