AXIS
====

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<options,OPTIONS>>
. <<see-also,SEE ALSO>>
. <<history,HISTORY>>
. <<bugs,BUGS>>
. <<author,AUTHOR>>
. <<reporting-bugs,REPORTING BUGS>>
. <<copyright,COPYRIGHT>>


===== [[name]]NAME
axis -- AXIS LinuxCNC Graphical User Interface


===== [[synopsis]]SYNOPSIS
axis
__-ini__ __INIFILE__


===== [[description]]DESCRIPTION
**axis** is one of the Graphical User Interfaces (GUI) for LinuxCNC 
It gets run by the runscript usually.


===== [[options]]OPTIONS

**INIFILE**
The ini file is the main piece of an LinuxCNC configuration. It is not the
entire configuration; there are various other files that go with it
(NML files, HAL files, TBL files, VAR files). It is, however, the most
important one, because it is the file that holds the configuration
together. It can adjust a lot of parameters itself, but it also tells
**LinuxCNC** which other files to load and use.



===== [[see-also]]SEE ALSO
**LinuxCNC(1)**

Much more information about LinuxCNC and HAL is available in the LinuxCNC
and HAL User Manuals, found at /usr/share/doc/LinuxCNC/.



===== [[history]]HISTORY



===== [[bugs]]BUGS
None known at this time. 
.PP


===== [[author]]AUTHOR
This man page written by Alex Joni, as part of the LinuxCNC project.


===== [[reporting-bugs]]REPORTING BUGS
Report bugs to alex_joni AT users DOT sourceforge DOT net


===== [[copyright]]COPYRIGHT
Copyright \(co 2007 Alex Joni.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
