HALTCL
======

. <<name,NAME>>
. <<synopsis,SYNOPSIS>>
. <<description,DESCRIPTION>>
. <<options,OPTIONS>>
. <<commands,COMMANDS>>
. <<reporting-bugs,REPORTING BUGS>>
. <<copyright,COPYRIGHT>>
. <<see-also,SEE ALSO>>
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
.if \n[.g] .mso www.tmac


===== [[name]]NAME
haltcl -- manipulate the LinuxCNC HAL from the command line using a tcl
interpeter.



===== [[synopsis]]SYNOPSIS
haltcl [__-i inifile__] [__filename__\]
.PP



===== [[description]]DESCRIPTION
**haltcl** is used to manipulate the HAL (Hardware Abstraction
Layer) from the command line using a tcl interpreter.  **haltcl**
can optionally read commands from a file (filename), allowing
complex HAL configurations to be set up with a single command.



===== [[options]]OPTIONS

**-i** __inifile__
If specified, the inifile is read and used to create tcl global variable
arrays.  An array is created for each SECTION of the inifile with
elements for each ITEM in the section.
.P
       For example, if the inifile contains:
       [SECTION_A]ITEM_1 =  1
       [SECTION_A]ITEM_2 =  2
       [SECTION_B]ITEM_1 = 10

       The corresponding tcl variables are:
       SECTION_A(ITEM_1) =  1
       SECTION_A(ITEM_2) =  2
       SECTION_B(ITEM_1) = 10

**-ini** __inifile__ -- declining usage, use **-i** __inifile__

**filename**
If specified, the tcl commands of **filename** are executed.  If no filename
is specified, haltcl opens an interactive session.



===== [[commands]]COMMANDS
**haltcl** includes the commands of a tcl interpreter augmented with
commands for the hal language as described for **halcmd**(1).  The augmented
commands can be listed with the command:

   haltcl: hal --commands

   addf alias delf delsig getp gets ptype stype help linkpp linkps linksp list loadrt loadusr lock net newsig save setexact_for_test_suite_only setp sets show source start status stop unalias unlinkp unload unloadrt unloadusr unlock waitusr

Two of the augmented commands, 'list' and 'gets', require special treatment to
avoid conflict with tcl built-in commands having the same names.  To use these
commands, precede them with the keyword 'hal':

   hal list
   hal gets



===== [[reporting-bugs]]REPORTING BUGS
Report bugs to the
.URL http://sf.net/tracker/?group_id=6744&atid=106744 "LinuxCNC bug tracker" .


===== [[copyright]]COPYRIGHT
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



===== [[see-also]]SEE ALSO
**halcmd**(1), **halrun**(1)
